package com.democode.mlmsittu.shared.storage.internal;

import com.democode.mlmsittu.shared.storage.api.DocumentStorage;
import com.democode.mlmsittu.shared.storage.api.StoredObjectRef;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.time.LocalDate;
import java.util.HexFormat;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Local-disk implementation of {@link DocumentStorage}.
 *
 * <p>Stands in for MinIO, which needs Docker. It preserves the properties that matter:
 *
 * <ul>
 *   <li><b>Outside the served tree.</b> Files live under a configured root that no controller maps
 *       and no static handler exposes. There is no URL that reaches them.
 *   <li><b>Unguessable keys.</b> 128 bits of randomness, so knowing one key tells you nothing
 *       about any other — the same reason S3 keys are not sequential.
 *   <li><b>No caller-supplied path.</b> Keys are generated here, never taken from a filename, so
 *       {@code ../../etc/passwd} has nowhere to go. {@link #resolve} re-checks containment anyway.
 * </ul>
 *
 * <p>Not encrypted at rest — architecture §7.1 expects SSE from the object store and an encrypted
 * volume underneath. On a laptop neither exists. <b>This implementation must not go to production;</b>
 * Phase 8 replaces it with S3.
 */
@Component
public class FilesystemDocumentStorage implements DocumentStorage {

    private static final Logger log = LoggerFactory.getLogger(FilesystemDocumentStorage.class);
    private static final SecureRandom RANDOM = new SecureRandom();

    private final Path root;

    public FilesystemDocumentStorage(
            @Value("${storage.filesystem.root:./var/documents}") String configuredRoot) {
        this.root = Path.of(configuredRoot).toAbsolutePath().normalize();
        try {
            Files.createDirectories(root);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not create document storage at " + root, e);
        }
        log.info("Document storage rooted at {} (local filesystem — not for production)", root);
    }

    @Override
    public StoredObjectRef put(byte[] content, String contentType, String kind) {
        // Date-sharded so a directory listing never grows to hundreds of thousands of entries,
        // which is where filesystem performance falls over.
        LocalDate today = LocalDate.now();
        byte[] randomBytes = new byte[16];
        RANDOM.nextBytes(randomBytes);

        String objectKey =
                "%s/%04d/%02d/%02d/%s%s"
                        .formatted(
                                kind,
                                today.getYear(),
                                today.getMonthValue(),
                                today.getDayOfMonth(),
                                HexFormat.of().formatHex(randomBytes),
                                extensionFor(contentType));

        Path target = resolve(objectKey);
        try {
            Files.createDirectories(target.getParent());
            Files.write(target, content, StandardOpenOption.CREATE_NEW);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not store document " + objectKey, e);
        }

        return new StoredObjectRef(objectKey, content.length, sha256(content));
    }

    @Override
    public byte[] get(String objectKey) {
        try {
            return Files.readAllBytes(resolve(objectKey));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not read document " + objectKey, e);
        }
    }

    @Override
    public void delete(String objectKey) {
        try {
            Files.deleteIfExists(resolve(objectKey));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not delete document " + objectKey, e);
        }
    }

    @Override
    public boolean exists(String objectKey) {
        return Files.exists(resolve(objectKey));
    }

    /**
     * Resolves a key inside the root and refuses anything that escapes it.
     *
     * <p>Keys are generated by this class, so traversal should be impossible already. The check is
     * here because "should be impossible" is how directory traversal keeps happening: one future
     * caller passes a key from a request, and without this line the storage root stops being a
     * boundary.
     */
    private Path resolve(String objectKey) {
        Path candidate = root.resolve(objectKey).normalize();
        if (!candidate.startsWith(root)) {
            throw new IllegalArgumentException("Object key escapes the storage root");
        }
        return candidate;
    }

    private static String extensionFor(String contentType) {
        return switch (contentType) {
            case "image/jpeg" -> ".jpg";
            case "image/png" -> ".png";
            case "application/pdf" -> ".pdf";
            default -> ".bin";
        };
    }

    private static String sha256(byte[] content) {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(content));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 unavailable", e);
        }
    }
}
